model: yolov5s-cls.pt
data: data/fer2013
epochs: 150
batch_size: 2048
imgsz: 48
nosave: false
cache: null
device: ''
workers: 8
project: runs\train-cls
name: exp
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: runs\train-cls\exp29
